### ISSUE TITLE
When I run this command, it prompts me that the package is not found.

### ISSUE THREAD

**Issue by fwiskevin** [botamochi6277/Feetech-microros#1]
![image](https://github.com/botamochi6277/Feetech-microros/assets/56289112/9e2d28ac-0451-444b-9044-44828fbddd5f)

**Comment by fwiskevin** [comment]
My system version is Ubuntu22.04, ROS version is Humble.

**Comment by botamochi6277** [comment]
Have you install micro_ros package?
If you have not install it, please install it first with reading [official tutorial](https://micro.ros.org/docs/tutorials/core/first_application_linux/)

**Comment by fwiskevin** [comment]
I have encountered a new problem.
![image](https://github.com/botamochi6277/Feetech-microros/assets/56289112/853ae1c6-6423-4d78-8acb-14db1e3cd049)

**Comment by botamochi6277** [comment]
This problem is related to micro_ros package, not  to this repository.
Discussion about it should be in ROS forum or micro_ros project page. Please ask questions about your problem in these pages.

**Comment by fwiskevin** [comment]
Thanks, I will try.
